import { Check, ChevronDown, ShieldAlert, ShieldCheck } from "lucide-react-native";
import { Modal, Pressable, Text, View } from "react-native";
import { useEffect, useState } from "react";
import { useWorkspace } from "./workspace";
import { colors, s } from "./ui";
type Mode = "ask_codex" | "ask_approval" | "approve_for_me";
const OPTIONS=[{id:"ask_codex" as Mode,title:"Ask Codex anything",detail:"Consulta e análise; nenhuma alteração externa é autorizada.",icon:ShieldCheck,danger:false},{id:"ask_approval" as Mode,title:"Ask for approval",detail:"O1 pausa antes de modificações, mensagens ou ações externas.",icon:ShieldCheck,danger:false},{id:"approve_for_me" as Mode,title:"Approve for me",detail:"O1 executa ações automaticamente enquanto este modo estiver ativo.",icon:ShieldAlert,danger:true}];
export function PermissionModePicker(){
 const {api}=useWorkspace(); const [mode,setMode]=useState<Mode>("ask_codex"); const [open,setOpen]=useState(false); const [confirm,setConfirm]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{let alive=true; void api.request<{mode:Mode}>("/api/o1/permissions").then(v=>{if(alive)setMode(v.mode}).catch(()=>{}); return()=>{alive=false}},[api]);
 async function save(next:Mode){setBusy(true);setError("");try{await api.request("/api/o1/permissions",{mode:next,confirm:next==="approve_for_me"},"PUT");setMode(next);setOpen(false);setConfirm(false)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const current=OPTIONS.find(x=>x.id===mode)??OPTIONS[0]; const Icon=current.icon;
 return <><Pressable accessibilityRole="button" accessibilityLabel={"Permission mode: "+current.title} onPress={()=>setOpen(true)} style={({pressed})=>({alignSelf:"flex-start",flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:12,paddingVertical:8,borderRadius:18,backgroundColor:mode==="approve_for_me"?"#FFE8E8":"#F2F5F7",borderWidth:mode==="approve_for_me"?1:0,borderColor:"#E24A4A",opacity:pressed?.82:1})}><Icon size={14} color={mode==="approve_for_me"?"#B42318":colors.text}/><Text style={{fontSize:13,fontWeight:"700",color:mode==="approve_for_me"?"#B42318":colors.text}}>{current.title}</Text><ChevronDown size={14} color={colors.muted}/></Pressable>
 <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={{flex:1,backgroundColor:"rgba(0,0,0,.38)",justifyContent:"flex-end"}}><Pressable style={{flex:1}} onPress={()=>setOpen(false)}/><View style={{backgroundColor:"#fff",borderTopLeftRadius:28,borderTopRightRadius:28,padding:20,gap:12}}><Text style={s.heading}>How should O1 act?</Text><Text style={s.muted}>You control how much autonomy the agent has.</Text>{OPTIONS.map(item=>{const I=item.icon;const selected=item.id===mode;return <Pressable key={item.id} onPress={()=>item.id==="approve_for_me"?setConfirm(true):void save(item.id)} style={({pressed})=>({flexDirection:"row",alignItems:"center",gap:13,padding:15,borderRadius:18,borderWidth:1,borderColor:item.danger?"#F1B2B2":selected?colors.blue:colors.line,backgroundColor:item.danger?"#FFF5F5":selected?colors.sky:"#fff",opacity:pressed||busy?.72:1})}><I size={21} color={item.danger?"#B42318":colors.text}/><View style={{flex:1,gap:3}}><Text style={s.heading}>{item.title}</Text><Text style={s.small}>{item.detail}</Text></View>{selected&&<Check size={19} color={colors.blueDark}/>}</Pressable>})}<Text style={{color:"#B42318",fontSize:13}}>{error}</Text><Pressable onPress={()=>setOpen(false)}><Text style={{textAlign:"center",fontWeight:"700",color:colors.muted}}>Cancel</Text></Pressable></View></View></Modal>
 <Modal visible={confirm} transparent animationType="fade" onRequestClose={()=>setConfirm(false)}><View style={{flex:1,backgroundColor:"rgba(30,0,0,.72)",justifyContent:"center",padding:20}}><View style={{backgroundColor:"#FFF1F1",borderRadius:26,padding:22,borderWidth:2,borderColor:"#D92D20",gap:14}}><View style={{flexDirection:"row",alignItems:"center",gap:10}}><ShieldAlert size={27} color="#B42318"/><Text style={{fontSize:21,fontWeight:"800",color:"#8A1C1C"}}>Approve for me</Text></View><Text style={{fontSize:15,lineHeight:22,color:"#5F1717"}}>Você tem certeza? O O1 poderá executar ações externas e modificações automaticamente, sem pedir confirmação a cada ação.</Text><View style={{flexDirection:"row",gap:10}}><Pressable onPress={()=>setConfirm(false)} style={{flex:1,padding:14,borderRadius:16,backgroundColor:"#fff",alignItems:"center"}}><Text style={{fontWeight:"800",color:"#5F1717"}}>Cancelar</Text></Pressable><Pressable disabled={busy} onPress={()=>void save("approve_for_me")} style={{flex:1,padding:14,borderRadius:16,backgroundColor:"#D92D20",alignItems:"center"}}><Text style={{fontWeight:"800",color:"#fff"}}>{busy?"Ativando…":"Sim, ativar"}</Text></Pressable></View></View></View></Modal>
 </>;
}